"""empty message

Revision ID: 356d8c75f68a
Revises: 4abaa646958d
Create Date: 2021-08-05 23:18:32.963624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356d8c75f68a'
down_revision = '4abaa646958d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
